actions:
  - from: iracelog
    update:
      - repo: iracelog-ansible-server-setup
        files: [group_vars/all/vars.yml]
        regex: '(?P<key>\s*iracelog_frontend_version:\s*)(?P<value>v.*?)(?P<other>$|\s+\.*)'
      - repo: iracelog-deployment
        files: [compose/docker-compose.yml]
        regex: '(?P<key>\s*image:\s*ghcr.io/mpapenbr/iracelog-web:)(?P<value>v.*?)(?P<other>$|\s+\.*)'
      - repo: iracelog-deployment
        files: [k8s/helm/iracelog-app/values.yaml]
        regex: '(?P<key>\s*iracelogVersion:\s*)(?P<value>v.*?)(?P<other>$|\s+\.*)'
      - repo: iracelog-documentation
        files: [versions.yml, README.adoc]
        regex: '(?P<key>\s*iracelog-web:\s*)(?P<value>v.*?)(?P<other>$|\s+\.*)'

      - repo: prod-provision
        branch: master
        repoType: Bitbucket
        files:
          [
            newlayout/roles/apps/iracelog/vars/main.yml,
            newlayout/roles/apps/iracelog-aer/vars/main.yml,
          ]
        regex: '(?P<key>\s*iracelog_frontend_version:\s*)(?P<value>v.*?)(?P<other>$|\s+\.*)'
      - repo: linux-provision
        repoType: Bitbucket
        files: [inventory/group_vars/all/iracelog.yml]
        regex: '(?P<key>\s*iracelog_frontend_version:\s*)(?P<value>v.*?)(?P<other>$|\s+\.*)'

  - from: iracelog-service-manager-go
    update:
      - repo: iracelog-ansible-server-setup
        files: [group_vars/all/vars.yml]
        regex: '(?P<key>\s*iracelog_ism_go_version:\s*)(?P<value>v?.*?)(?P<other>$|\s+\.*)'
      - repo: iracelog-deployment
        files: [compose/docker-compose.yml]
        regex: '(?P<key>\s*image:\s*ghcr.io/mpapenbr/iracelog-service-manager-go:)(?P<value>v?.*?)(?P<other>$|\s+\.*)'
      - repo: iracelog-deployment
        files: [k8s/helm/iracelog-app/values.yaml]
        regex: '(?P<key>\s*ismVersion:\s*)(?P<value>v?.*?)(?P<other>$|\s+\.*)'
      - repo: iracelog-documentation
        files: [versions.yml, README.adoc]
        regex: '(?P<key>\s*iracelog-service-manager-go:\s*)(?P<value>v?.*?)(?P<other>$|\s+\.*)'
      - repo: prod-provision
        branch: master
        repoType: Bitbucket
        files:
          [
            newlayout/roles/apps/iracelog/vars/main.yml,
            newlayout/roles/apps/iracelog-aer/vars/main.yml,
          ]
        regex: '(?P<key>\s*iracelog_ism_go_version:\s*)(?P<value>v?.*?)(?P<other>$|\s+\.*)'
      - repo: linux-provision
        repoType: Bitbucket
        files: [inventory/group_vars/all/iracelog.yml]
        regex: '(?P<key>\s*iracelog_ism_go_version:\s*)(?P<value>v?.*?)(?P<other>$|\s+\.*)'

  - from: iracelog-wamp-router
    update:
      - repo: iracelog-ansible-server-setup
        files: [group_vars/all/vars.yml]
        regex: '(?P<key>\s*iracelog_wamp_router:\s*)(?P<value>v.*?)(?P<other>$|\s+\.*)'
      - repo: iracelog-deployment
        files: [compose/docker-compose.yml]
        regex: '(?P<key>\s*image:\s*ghcr.io/mpapenbr/iracelog-wamp-router:)(?P<value>v.*?)(?P<other>$|\s+\.*)'
      - repo: iracelog-deployment
        files: [k8s/helm/iracelog-app/values.yaml]
        regex: '(?P<key>\s*iwrVersion:\s*)(?P<value>v.*?)(?P<other>$|\s+\.*)'
      - repo: iracelog-documentation
        files: [versions.yml, README.adoc]
        regex: '(?P<key>\s*iracelog-wamp-router:\s*)(?P<value>v.*?)(?P<other>$|\s+\.*)'
      - repo: prod-provision
        branch: master
        repoType: Bitbucket
        files:
          [
            newlayout/roles/apps/iracelog/vars/main.yml,
            newlayout/roles/apps/iracelog-aer/vars/main.yml,
          ]
        regex: '(?P<key>\s*iracelog_iwr_version:\s*)(?P<value>v.*?)(?P<other>$|\s+\.*)'
      - repo: linux-provision
        repoType: Bitbucket
        files: [inventory/group_vars/all/iracelog.yml]
        regex: '(?P<key>\s*iracelog_iwr_version:\s*)(?P<value>v.*?)(?P<other>$|\s+\.*)'

  - from: iracelog-graphql
    update:
      - repo: iracelog-ansible-server-setup
        files: [group_vars/all/vars.yml]
        regex: '(?P<key>\s*iracelog_graphql_version:\s*)(?P<value>v.*?)(?P<other>$|\s+\.*)'
      - repo: iracelog-deployment
        files: [compose/docker-compose.yml]
        regex: '(?P<key>\s*image:\s*ghcr.io/mpapenbr/iracelog-graphql:)(?P<value>v.*?)(?P<other>$|\s+\.*)'
      - repo: iracelog-deployment
        files: [k8s/helm/iracelog-app/values.yaml]
        regex: '(?P<key>\s*graphqlVersion:\s*)(?P<value>v.*?)(?P<other>$|\s+\.*)'
      - repo: iracelog-documentation
        files: [versions.yml, README.adoc]
        regex: '(?P<key>\s*iracelog-graphql:\s*)(?P<value>v.*?)(?P<other>$|\s+\.*)'
      - repo: prod-provision
        branch: master
        repoType: Bitbucket
        files:
          [
            newlayout/roles/apps/iracelog/vars/main.yml,
            newlayout/roles/apps/iracelog-aer/vars/main.yml,
          ]
        regex: '(?P<key>\s*iracelog_graphql_version:\s*)(?P<value>v.*?)(?P<other>$|\s+\.*)'
      - repo: linux-provision
        repoType: Bitbucket
        files: [inventory/group_vars/all/iracelog.yml]
        regex: '(?P<key>\s*iracelog_graphql_version:\s*)(?P<value>v.*?)(?P<other>$|\s+\.*)'

  - from: go-racelogger
    update:
      - repo: iracelog-documentation
        files: [versions.yml, README.adoc]
        regex: '(?P<key>\s*racelogger:\s*)(?P<value>v.*?)(?P<other>$|\s+\.*)'

  - from: racelogctl
    update:
      - repo: iracelog-documentation
        files: [versions.yml, README.adoc]
        regex: '(?P<key>\s*racelogctl:\s*)(?P<value>v.*?)(?P<other>$|\s+\.*)'

  - from: iracelog-cli
    update:
      - repo: iracelog-documentation
        files: [versions.yml, README.adoc]
        regex: '(?P<key>\s*iracelog-cli:\s*)(?P<value>v.*?)(?P<other>$|\s+\.*)'
      - repo: linux-provision
        repoType: Bitbucket
        files: [inventory/group_vars/all/iracelog.yml]
        regex: '(?P<key>\s*iracelog_cli_version:\s*)(?P<value>v.*?)(?P<other>$|\s+\.*)'

  - from: istint
    update:
      - repo: prod-provision
        branch: master
        repoType: Bitbucket
        files: [newlayout/roles/apps/istint/vars/main.yml]
        regex: '(?P<key>\s*istint_frontend_version:\s*)(?P<value>v.*?)(?P<other>$|\s+\.*)'

  - from: istint-backend
    update:
      - repo: prod-provision
        branch: master
        repoType: Bitbucket
        files: [newlayout/roles/apps/istint/vars/main.yml]
        regex: '(?P<key>\s*istint_backend_version:\s*)(?P<value>v.*?)(?P<other>$|\s+\.*)'
